- name: Check if zsh-autosuggestions is installed
  stat:
    path: "~/.zsh/plugins/zsh-autosuggestions"
  register: zshautosuggestions_path

- name: Install zsh-autosuggestions
  when: zshautosuggestions_path.stat.isdir is not defined
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.zsh/plugins/zsh-autosuggestions"


- name: Check if zsh-history-substring-search is installed
  stat:
    path: "~/.zsh/plugins/zsh-history-substring-search"
  register: zsh_history_substring_search_path

- name: Install zsh-history-substring-search
  when: zsh_history_substring_search_path.stat.isdir is not defined
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-history-substring-search.git'
    dest: "~/.zsh/plugins/zsh-history-substring-search"


- name: Check if zsh-syntax-highlighting is installed
  stat:
    path: "~/.zsh/plugins/zsh-syntax-highlighting"
  register: zsh_syntax_highlighting_exists

- name: Install zsh-syntax-highlighting
  # when: zsh_syntax_highlighting_exists.stat.isdir is not defined
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "~/.zsh/plugins/zsh-syntax-highlighting"
    update: yes

- name: Check if zsh-vi-mode is installed
  stat:
    path: "~/.zsh/plugins/zsh-vi-mode"
  register: zsh_vi_mode_exists

- name: Install zsh-vi-mode
  when: zsh_vi_mode_exists.stat.isdir is not defined
  ansible.builtin.git:
    repo: 'https://github.com/jeffreytse/zsh-vi-mode.git'
    dest: "~/.zsh/plugins/zsh-vi-mode"


- name: Check if forgit is installed
  stat:
    path: "~/.forgit"
  register: forgit_exists
  tags: 
    - forgit

- name: Install Forgit
  when: forgit_exists.stat.isdir is not defined
  ansible.builtin.git:
    repo: "https://github.com/wfxr/forgit"
    dest: "~/.forgit"

