# - name: Change shell to zsh
#   become_user: root
#   shell: chsh -s /usr/bin/zsh {{ user }}


- name: Check if zsh-autosuggestions is installed
  stat:
    path: "~/.zsh/plugins/zsh-autosuggestions"
  register: zshautosuggestions_path

- name: Install zsh-autosuggestions
  when: zshautosuggestions_path.stat.islnk is not defined
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.zsh/plugins/zsh-autosuggestions"


- name: Check if zsh-history-substring-search is installed
  stat:
    path: "~/.zsh/plugins/zsh-history-substring-search"
  register: zsh_history_substring_search_path

- name: Install zsh-history-substring-search
  when: zsh_history_substring_search_path.stat.islnk is not defined
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-history-substring-search.git'
    dest: "~/.zsh/plugins/zsh-history-substring-search"


- name: Check if zsh-syntax-highlighting is installed
  stat:
    path: "~/.zsh/plugins/zsh-syntax-highlighting"
  register: zsh_syntax_highlighting_exists

- name: Install zsh-syntax-highlighting
  when: zsh_syntax_highlighting_exists.stat.islnk is not defined
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "~/.zsh/plugins/zsh-syntax-highlighting"

- name: Check if zsh-vi-mode is installed
  stat:
    path: "~/.zsh/plugins/zsh-vi-mode"
  register: zsh_vi_mode_exists

- name: Install zsh-vi-mode
  when: zsh_vi_mode_exists.stat.islnk is not defined
  ansible.builtin.git:
    repo: 'https://github.com/jeffreytse/zsh-vi-mode.git'
    dest: "~/.zsh/plugins/zsh-vi-mode"


- name: Check if forgit is installed
  stat:
    path: "~/.forgit"
  register: forgit_exists
  tags: 
    - forgit

# - name: Install Forgit
#   when: forgit_exists is failed
#   shell: git clone https://github.com/wfxr/forgit ~/.forgit
#   tags:
#     - forgit

- name: Install Forgit
  when: forgit_exists.stat.islnk is not defined
  ansible.builtin.git:
    repo: "https://github.com/wfxr/forgit"
    dest: "~/.forgit"


# VIFM INSTALL
# - name: check is vifm installed
#   shell: command -v vifm
#   register: vifm_exists
#   ignore_errors: yes
#   tags: 
#     - vifm

# - name: Install vifm
#   when: vifm_exists is failed
#   shell: | 
#     VIFM_VERSION=$(curl --silent https://github.com/vifm/vifm/releases/latest | tr -d '"' | sed 's/^.*tag\///g' | sed 's/>.*$//g' | sed 's/^v//')
#     wget https://github.com/vifm/vifm/releases/download/v${VIFM_VERSION}/vifm-v${VIFM_VERSION}-x86_64.AppImage -O ~/.local/bin/vifm
#     chmod +x ~/.local/bin/vifm
#   tags:
#     - vifm

