#!/usr/bin/env bash

PROJECTS_PATHS=(
	~/projects
	~/projects/fermyon
	~/projects/diligent
	~/projects/pact-foundation
	~/projects/flux
	~/projects/wasmcloud
	~/projects/nvim-configs/
)

EXISTING_PROJECTS_PATHS=()

for index in "${!PROJECTS_PATHS[@]}"; do
	if [ -d "${PROJECTS_PATHS[$index]}" ]; then
		EXISTING_PROJECTS_PATHS+=("${PROJECTS_PATHS["$index"]}")
	fi
done

if [[ $# -eq 1 ]]; then
	selected=$1
else
	selected=$(find "${EXISTING_PROJECTS_PATHS[@]}" -mindepth 1 -maxdepth 1 -type d | fzf --header 'jump-to-project')
fi

if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr . _)
# tmux_running=$(pgrep tmux)

SESSION_NAME=$selected_name START_DIR=$selected tmuxp load -y default
