session_name: ${SESSION_NAME}
windows:
- window_name: editor
  layout: main-vertical
  start_directory: ${START_DIR}
  shell_command_before:
    - v 
- window_name: git
  window_index: 2
  layout: tiled
  start_directory: ${START_DIR}
  shell_command_before:
    - lg
