#!/usr/bin/env bash

DOTFILES_FOLDERS="
  tmux,
  hypr,
  git,
  helix,
  nvim,
  zsh,
  lazygit,
  starship,
  kitty,
  ghostty,
  zellij,
  opencode,
  scripts
"

for folder in $(echo $DOTFILES_FOLDERS | sed "s/,/ /g"); do
  stow -vSt ~ $folder
done
