#!/usr/bin/env bash
DOTFILES_FOLDERS="
  bin,
  dunst,
  hypr,
  git,
  kitty,
  nvim,
  helix,
  lazygit,
  starship,
  qt5ct,
  qt6ct,
  rofi,
  tmux,
  swappy,
  swaync,
  waybar,
  wallust,
  zsh,
  wlogout,
  ghostty
"

for folder in $(echo $DOTFILES_FOLDERS | sed "s/,/ /g"); do
	stow -vSt ~ $folder
done
