#!/usr/bin/env bash
DOTFILES_FOLDERS="
  bin,
  lvim, 
  tmux,
  hypr,
  wlogout,
  git,
  nvim,
  zsh,
  lazygit,
  alacritty,
  starship,
  kitty,
  i3,
  rofi,
  xorg,
  waybar
  dunst
"

for folder in $(echo $DOTFILES_FOLDERS | sed "s/,/ /g"); do
	stow -vSt ~ $folder
done
