#!/usr/bin/env bash
DOTFILES_FOLDERS="
  kitty,
  lvim, 
  tmux,
  git,
  hammerspoon,
  nvim,
  zsh,
  lazygit,
  karabiner
"

for folder in `echo $DOTFILES_FOLDERS | sed "s/,/ /g"` 
do
 stow -vSt ~ $folder
done

