theme = "tokyonight-ext"

[editor]
line-number = "relative"
mouse = true
preview-completion-insert = false
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.indent-guides]
render = true
skip-levels = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false


[keys.normal]
D = "@vgld"
C = "@vglc"
'^' = "@gs"
'$' = "@gl"
S-k = "hover"
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-e = "@9zj"
C-y = "@9zk"
C-d = "@5j"
C-u = "@5k"
C-s = ":write"          # Ctrl and 's' to write

[keys.insert.j]
j = "normal_mode"

[keys.insert]
C-s = ["normal_mode", ":write"]

[keys.normal.space]
Q = ":write-quit-all!"
# e = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- sh ~/.config/helix/nnn-picker.sh"

[keys.normal.space.u]
h = ":toggle lsp.display-inlay-hints"
