theme = "tokyonight"

[editor]
line-number = "relative"
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false


[keys.normal]
S-k = "hover"
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-e = "@9zj"
C-y = "@9zk"
C-d = "@5j"
C-u = "@5k"
C-s = ":write" # Ctrl and 's' to write

[keys.insert.j]
j = "normal_mode"


[keys.normal.space]
Q = ":qa"
e = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- sh ~/.config/helix/nnn-picker.sh"

[keys.normal.space.u]
h = ":toggle lsp.display-inlay-hints"
