- name: (OSX) Install System Packages for building nvim
  homebrew:
    name: "{{ item }}"
  loop:
    - ninja
    - libtool
    - automake
    - cmake
    - pkg-config
    - gettext
    - curl
      
- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "~/neovim"
    update: yes

- name: Build neovim
  shell: "cd ~/neovim && sudo make"

- name: Install neovim
  shell: "cd ~/neovim && sudo make install"

