- name: "[macOS] Check for software updates daily, not just once per week"
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: ScheduleFrequency
    type: integer
    value: 1
    state: present

- name: "[macOS] Disable smart quotes"
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false
    state: present

- name: "[macOS] Disable smart dashes"
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: false
    state: present

- name: "[macOS] Trackpad - enable tap to click for this user and for the login screen"
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    type: integer
    value: 1
    state: present

- name: "[macOS] Trackpad - enable tap to click for this user and for the login screen"
  osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: integer
    value: 1
    state: present

- name: "[macOS] Disable press-and-hold for keys in favor of key repeat"
  osx_defaults:
    domain: NSGlobalDomain
    key: ApplePressAndHoldEnabled
    type: bool
    value: false
    state: present

- name: "[macOS] Set a blazingly fast keyboard repeat rate"
  osx_defaults:
    domain: NSGlobalDomain
    key: KeyRepeat
    type: integer
    value: 2
    state: present

- name: "[macOS] Set a short keyboard repeat rate delay"
  osx_defaults:
    domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: integer
    value: 15
    state: present

- name: "[macOS] Increase speed of trackpad cursor movement"
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.trackpad.scaling
    type: float
    value: 3
    state: present

- name: "[macOS] Set three-finger drag"
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.trackpad.threeFingerSwipeGesture
    type: integer
    value: 1 
    state: present
