- name: "[brew] Configure Homebrew taps"
  homebrew_tap:
    name: "{{ item }}"
  loop: "{{ brew_taps }}"

- name: "[brew] Install Homebrew formulae"
  homebrew:
    name: "{{ item }}"
  loop: "{{ brew_packages }}"

