brew_taps:
  - homebrew/cask-versions
  - homebrew/cask-fonts
  - aws/tap

brew_packages:
  - ansible
  - bat
  - coreutils
  - exa
  - go
  - htop
  - nmap
  - tmux
  - tmuxp
  - fd
  - fzf
  - broot
  - stow
  - zsh
  - git-delta
  - gh
  - ripgrep
  - pipx
  - starship
  - fnm
  - pyenv
  - ffmpeg
  - gifsicle
  - restic # backups

  # infrastructure 
  - terraform
  - awscli
  - aws-vault
  - aws-sam-cli

# cask_packages:
  # - docker
  # - google-chrome
  # - kitty
  # - visual-studio-code
  # - vagrant
  # - spotify

