- name: Setup workstation 
  hosts: localhost
  gather_facts: true
  become: true
  become_user: "{{ lookup('env', 'USER') }}"

  vars:
    user: "{{ ansible_user_id }}"
  roles: 
    # - core-setup
    - zsh
    # - neovim
    # - osx-defaults

